### ISSUE TITLE
update list of files in kwl.md

### ISSUE THREAD

**Issue by olwmc** [introcompsys/spring2022#61]
You asked me in class to tell you to add something for this task:

*write a script that outputs the first 3 lines of each .fastq line and sbatch script that runs it and saves the output to files and e-mails you when it is done. Submit the job. (to reinforce /practice what we saw in class)*

**Comment by brownsarahm** [comment]
You asked me a question and there was an answer that i had at that time and that I no longer remember the question

**Comment by olwmc** [comment]
I'm not sure if this was resolved, but i was referring to:
```
priority write a script that outputs the first 3 lines of each .fastq line and sbatch script that runs it and saves the output to files and e-mails you when it is done. Submit the job. (to reinforce /practice what we saw in class)
```
I wasn't sure how we might document that we actually did this.

**Comment by brownsarahm** [comment]
ohhh okay for that, add the script(s) to your repo. I'll update to clarify that when I make this other update.
